package view;

public enum ScreenNames {
  INITIAL_SCREEN,
  MAIN_SCREEN,
  LOAD_USER_SCREEN,
  CREATE_PORTFOLIO_SCREEN,
  GET_COST_BASIS_SCREEN,
  GET_TOTAL_VALUE_SCREEN,
  INVEST_ON_DATE,
  LOAD_PORTFOLIO_SCREEN,
  SELL_STOCKS_SCREEN,
  BUY_STOCKS_SCREEN,
  LIST_OF_PORTFOLIOS_SCREEN, NEW_USER_SCREEN, CREATE_USER_SCREEN


};
