package view;

public enum ScreenNames {
  INITIAL_SCREEN,
  MAIN_SCREEN,
  LOAD_USER_SCREEN, CREATE_PORTFOLIO_SCREEN, GET_COST_BASIS_SCREEN, GET_TOTAL_VALUE_SCREEN, INVEST_ON_DATE, CREATE_USER_SCREEN


};
